config/routes.rb
Rails.application.routes.draw do
  get "static_pages/home"
  resource :session, except: [ :new ]

  # keep commented out unless password mailers are needed
  # resources :passwords, param: :token


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker


  root "static_pages#home"

  get "terms-of-use",   to: "static_pages#terms"
  get "privacy-policy", to: "static_pages#privacy"
  get "password-reset", to: "static_pages#password_reset"

  get "signup",   to: "registrations#new"
  post "signup",  to: "registrations#create"
  get "login",    to: "sessions#new"
  get "settings", to: "registrations#edit"
  resource :registrations, except: [ :show ]
  resources :plants, except: [ :index, :show ]
  resources :categories, except: [ :show ]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  allow_unauthenticated_access

  def home
    if authenticated?
      @categories = Current.user.categories
      @plants = filter_plants
      params[:category].nil? ? @selected_category = "All Plants" : @selected_category = params[:category]
    end
  end

  def terms
  end

  def privacy
  end

  def password_reset
  end

  private

    def filter_plants
      if params[:category].present? && valid_category?(params[:category])
        Current.user.plants.joins(:categories).where(categories: { name: params[:category] }).order(created_at: :desc)
      else
        Current.user.plants.order(created_at: :desc)
      end
    end

    def valid_category?(category)
      Category.exists?(name: category)
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_logged_in_users.html.erb
<section class="section">
  <div class="is-flex is-justify-content-center is-flex-wrap-wrap">
    <% @categories.each do |category| %>
      <%= link_to root_path(category: category.name), data: { turbo_frame: "plant-index" }, class: "card p-2 m-1 is-green has-text-white has-text-centered" do %>
        <p class="is-size-6 is-size-7-mobile has-text-weight-bold">
          <%= category.name %>
        </p>
      <% end %>
    <% end %>
  </div>

  <div class="my-5">
    <turbo-frame id="plant-index">
      <% if @plants.count.zero? %>
        <div class="container my-6 has-text-centered">
          <div class="columns is-centered">
            <div class="column is-half">
              <div class="card">
                <div class="card-content">
                  <p class="is-size-4 has-text-black block">No plants found. Click the button below to add one.</p>
                  <%= link_to "Add Plant", new_plant_path, class: "button is-green has-text-white has-text-weight-semibold is-medium", data: { turbo_frame: "_top" } %>
                </div>
              </div>
            </div>
          </div>
        </div>
      <% else %>
        <div class="is-flex is-flex-direction-column mb-6">
          <h1 class="is-size-2 is-size-3-mobile has-text-weight-semibold mb-2"><%= @selected_category %> (<%= @plants.count %>)</h1>  
          <div class="buttons">
            <%= link_to "Add Plant", new_plant_path, class: "button is-green has-text-white has-text-weight-semibold is-medium my-0 mx-0", data: { turbo: false } %>
            <% if @selected_category != "All Plants" %>
              <%= link_to "Reset", root_path(category: "All Plants"), class: "button is-red has-text-white has-text-weight-semibold is-medium my-0 mr-0" %>
            <% end %>
          </div>
        </div>
        <div class="fixed-grid has-5-cols-desktop has-3-cols-tablet has-1-cols-mobile">
          <div class="grid">
            <% @plants.each do |plant| %>
              <div class="card p-4 is-flex is-flex-direction-column is-justify-content-space-between" id="plant-card">
                <div class="is-flex is-flex-direction-column is-justify-content-start mb-4">
                  <p class="has-text-weight-semibold is-size-4"><%= "#{plant.common_name}" %></p>
                  <p class="is-size-6 is-italic"><%= "#{plant.taxonomic_name}" %></p>
                  <div class="is-flex is-flex-wrap-wrap my-1">
                    <% plant.categories.each do |category| %>
                      <span class="is-size-7 m-1">#<%= category.name.delete(" ") %></span>
                    <% end %>
                  </div>
                </div>
                <div class="actions">
                  <%= link_to "Edit", edit_plant_path(plant), class: "button is-green has-text-white has-text-weight-semibold", data: { turbo: "false" } %>
                  <%= link_to "Delete", plant_path(plant), data: { "turbo-method": :delete, turbo_confirm: "Are you sure you want to delete this plant?" }, class: "button is-red has-text-white has-text-weight-semibold" %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </turbo-frame>
  </div>
</section>

app/views/static_pages/_non_logged_in_users.html.erb
<section class="hero is-medium">
  <div class="hero-body">
    <div class="container">
      <div class="columns is-centered">
        <div class="column is-three-fifths is-full-touch">
          <div class="hero-container">
            <h1 class="is-size-2 is-size-3-mobile has-text-green has-text-weight-bold has-text-centered mb-2">Welcome to PlantSort</h1>
            <p class="is-size-4 is-size-5-mobile has-text-black has-text-centered mb-5">PlantSort is a free, open-source tool that helps you easily organize and manage the plants you grow with intuitive categories and a visually dynamic interface. Think of it as an enhanced spreadsheet, designed to let you view and organize your plants seamlessly across multiple contexts.</p>
            <div class="buttons is-centered">
              <%= link_to "Sign Up For Free", signup_path, class: "button has-text-white has-text-weight-semibold is-green is-medium" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="section mt-6">
  <div class="columns is-vcentered is-centered">
    <div class="column is-half is-full-mobile">
      <div class="has-text-left">
        <h2 class="is-size-2 is-size-3-mobile has-text-green has-text-weight-bold mb-5 has-text-left">Organize Your Plants By Context</h2>
      </div>
      <div class="has-text-left mb-5">
        <p class="is-size-3 is-size-4-touch has-text-green has-text-weight-bold mb-2">
          See the Big Picture
        </p>
        <p class="is-size-4 is-size-5-touch has-text-black block">
          View and organize your plants dynamically, helping you decide what to plant where—whether it's filling shaded beds or planning your perennial orchard.
        </p>
      
        <p class="is-size-3 is-size-4-touch has-text-green has-text-weight-bold mb-2">
          Adapt to Your Garden's Needs
        </p>
        <p class="is-size-4 is-size-5-touch has-text-black block">
          Quickly filter plants by categories like 'Perennials,' 'Fruits,' or 'Green Manures' to plan your garden with ease. 
        </p>

        <p class="is-size-3 is-size-4-touch has-text-green has-text-weight-bold mb-2">
          Customize Your Categories
        </p>
        <p class="is-size-4 is-size-5-touch has-text-black block">
          Sort plants your way. Create custom categories to tailor the app to your unique garden vision.
        </p>
      
        <p class="is-size-3 is-size-4-touch has-text-green has-text-weight-bold mb-2">
          Save Time, Grow Better
        </p>
        <p class="is-size-4 is-size-5-touch has-text-black block">
          Spend less time on planning and more time growing. PlantSort’s intuitive interface makes organizing plants effortless.
        </p>
      </div>
    </div>
  </div>
</section>

<section class="section my-6">
  <div class="columns is-vcentered is-centered">
    <div class="column is-half is-full-mobile is-flex is-flex-direction-column is-align-items-center">
      <h2 class="is-size-2 is-size-3-mobile has-text-green has-text-weight-bold block">See It In Action</h2>
      <%= image_tag "plantsort-dash.gif", alt: "GIF of PlantSort in action." %>
    </div>
  </div>
</section>

<section class="section my-6">
  <div class="columns is-vcentered is-centered">
    <div class="column is-half is-full-mobile is-flex is-flex-direction-column is-align-items-center">
      <h2 class="is-size-2 is-size-3-mobile has-text-green has-text-weight-bold block">Ready to Organize Your Plants?</h2>
      <div class="buttons is-centered">
        <%= link_to "Sign Up For Free", signup_path, class: "button has-text-white has-text-weight-semibold is-green is-medium" %>
      </div>
    </div>
  </div>
</section>

app/views/static_pages/home.html.erb
<% if @plants %>
  <%= render "logged_in_users" %>
<% else %>
  <%= render "non_logged_in_users" %>
<% end %>

app/views/static_pages/password_reset.html.erb
<% provide(:title, "Password Reset") %>

<section class="section is-medium">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-four-fifths is-full-mobile">
        <div class="has-text-centered">
          <p class="is-size-2 is-size-3-mobile has-text-green has-text-weight-medium mb-3">Password Reset</p>
          
          <p class="is-size-4 is-size-5-mobile block">This application is a passion project. Since it's impossible to tell if this application will gain any traction, there is not currently any infrastructure to automatically send you a reset password email. If you forgot your password and need it reset, please send an email to <%= mail_to "plantsortapp@gmail.com", "plantsortapp@gmail.com", class: "has-text-link"%> from the email address associated with your account and you will recieve a response containing a password reset link within a few hours.</p>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/static_pages/privacy.html.erb
<% provide(:title, "Privacy Policy") %>

<section class="section">
  <div class="container">
    <h1 class="is-size-1 has-text-weight-bold">Privacy Policy</h1>
    <h2 class="is-size-3 block">Effective Date: November 13th, 2024</h2>

    <div class="content">
      <p>
        At PlantSort, we are committed to protecting your privacy. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you use our application, website, and services (collectively, the “Services”). By accessing or using our Services, you agree to the terms of this Privacy Policy. If you do not agree, please do not use our Services.
      </p>

      <h2 class="subtitle">1. Information We Collect</h2>
      <p>We collect the following personal information from users:</p>
      <ul>
          <li><strong>Personal Information:</strong> When you create an account, we collect personal information such as your email address and password.</li>
          <li><strong>Usage Data:</strong> We may collect information about how you use our Services, including your browser type, access times, and pages viewed. We do not log IP addresses.</li>
          <li><strong>Cookies and Tracking Technologies:</strong> We may use first-party cookies and similar tracking technologies to monitor activity on our Services and store certain information. We do not use any third-party cookies.</li>
      </ul>

      <h2 class="subtitle">2. How We Use Your Information</h2>
      <p> We may use the information we collect for various purposes, including:</p>
      <ul>
        <li>To provide, maintain, and improve our Services.</li>
        <li>To communicate with you.</li>
        <li>To analyze usage patterns and improve user experience.</li>
        <li>To enforce our Terms of Service and other policies.</li>
      </ul>
    
      <h2 class="subtitle">3. Sharing Your Information</h2>
      <p>
        We do not sell, trade, or otherwise transfer your Personal Information to outside parties, except in the following circumstances:
      </p>
      <ul>
        <li><strong>Service Providers:</strong> We may share your information with third-party service providers to assist with email deliver efforts (i.e. we cannot send you a password reset email if we do not share your email address with SendGrid).</li>
        <li><strong>Legal Requirements:</strong> We may disclose your information if required to do so by law or in response to valid requests by public authorities. This is unlikely to ever happen though since this is a plant categorizing application.</li>
      </ul>

      <h2 class="subtitle">4. Data Security</h2>
      <p>
        We take reasonable measures to protect the information we collect from loss, theft, misuse, and unauthorized access. However, no method of transmission over the Internet or electronic storage is 100% secure. Therefore, we cannot guarantee its absolute security.
      </p>

      <h2 class="subtitle">5. Your Rights</h2>
      <p>
        Regardless of where you live, you have the following rights regarding your personal information:
      </p>
      <ul>
        <li>The right to access the information we hold about you.</li>
        <li>The right to request correction of any inaccurate information.
        </li>
        <li>The right to request deletion of your personal information.</li>
        <li>The right to withdraw your consent at any time where we rely on your consent to process your personal information.</li>
      </ul>

      <h2 class="subtitle">6. Changes to This Privacy Policy</h2>
      <p>
        We may update this Privacy Policy from time to time. Any changes will be effective upon posting the revised Privacy Policy in the app or on our website. Your continued use of the Services after changes are posted constitutes your acceptance of the revised Privacy Policy.
      </p>

      <h2 class="subtitle">7. Contact Us</h2>
      <p>
        If you have any questions about this Privacy Policy, please contact us at <%= mail_to "plantsortapp@gmail.com", "plantsortapp@gmail.com", class: "has-text-link"%>.
      </p>
      
    </div>
  </div>

app/views/static_pages/terms.html.erb
<% provide(:title, "Terms of Use") %>

<section class="section">
  <div class="container">
    <h1 class="is-size-1 has-text-weight-bold">Terms of Use</h1>
    <h2 class="is-size-3 block">Effective Date: November 13th, 2024</h2>

    <div class="content">
      <p>
        Welcome to PlantSort. These Terms of Use (“Terms”) govern your use of our application, website, and services (collectively, the “Services”). By accessing or using the Services, you agree to these Terms. If you do not agree, please do not use our Services.
      </p>

      <h2 class="subtitle">1. Acceptance of Terms</h2>
      <p>
        By using the Services, you affirm that you are at least 18 years old. If you are using the Services on behalf of an organization, you represent and warrant that you have the authority to bind that organization to these Terms.
      </p>

      <h2 class="subtitle">2. Changes to Terms</h2>
      <p>
        We may update these Terms from time to time. Any changes will be effective upon posting the revised Terms in the app or on our website. Your continued use of the Services after changes are posted constitutes your acceptance of the revised Terms.
      </p>

      <h2 class="subtitle">3. User Accounts</h2>
      <p>
        To use the main features of our Services, you will need to create an account. You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You agree to notify us immediately of any unauthorized use of your account.
      </p>

      <h2 class="subtitle">4. Disclaimer of Warranties</h2>
      <p>
        The Services are provided on an “as-is” and “as-available” basis. We do not warrant that the Services will be uninterrupted, secure, or error-free. Your use of the Services is at your own risk.
      </p>

      <h2 class="subtitle">5. Limitation of Liability</h2>
      <p>
        To the fullest extent permitted by law, PlantSort shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the Services.
      </p>

      <h2 class="subtitle">6. Governing Law</h2>
      <p>These Terms are governed by the laws of the United States of America.</p>

      <h2 class="subtitle">7. Contact Us</h2>
      <p>
        If you have any questions about these Terms, please contact us at <%= mail_to "plantsortapp@gmail.com", "plantsortapp@gmail.com", class: "has-text-link"%>.
      </p>
    </div>
  </div>
</section>