config/routes.rb
Rails.application.routes.draw do
  get "static_pages/home"
  resource :session, except: [ :new ]

  # keep commented out unless password mailers are needed
  # resources :passwords, param: :token


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker


  root "static_pages#home"

  get "terms-of-use",   to: "static_pages#terms"
  get "privacy-policy", to: "static_pages#privacy"
  get "password-reset", to: "static_pages#password_reset"

  get "signup",   to: "registrations#new"
  post "signup",  to: "registrations#create"
  get "login",    to: "sessions#new"
  get "settings", to: "registrations#edit"
  resource :registrations, except: [ :show ]
  resources :plants, except: [ :index, :show ]
  resources :categories, except: [ :show ]
end

app/models/plant.rb
class Plant < ApplicationRecord
  belongs_to :user
  validates :user, presence: true
  has_and_belongs_to_many :categories

  validates :common_name, presence: true, length: { maximum: 25 }
  validates :taxonomic_name, length: { maximum: 40 }

  validate :must_have_at_least_one_category

  private

  def must_have_at_least_one_category
    if category_ids.empty?
      errors.add(:base, "Each plant must belong to at least one category")
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :sessions,   dependent: :destroy
  has_many :plants,     dependent: :destroy
  has_many :categories, dependent: :destroy

  after_create :add_default_categories

  VALID_EMAIL_REGEX = URI::MailTo::EMAIL_REGEXP

  validates :email_address, presence: true, length: { minimum: 8, maximum: 50 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  normalizes :email_address, with: ->(e) { e.strip.downcase }

  private
    def add_default_categories
      default_categories = Category.where(user_id: nil)
      default_categories.each do |category|
        self.categories.create(name: category.name)
      end
    end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  before_action :set_plant, only: [ :edit, :update, :destroy ]
  def new
    @plant = Plant.new
    @categories = Current.user.categories
  end

  def create
    # Ensure category_ids is an array (in case of unselected checkboxes)
    params[:plant][:category_ids] ||= []

    @plant = Current.user.plants.new(plant_params)
    @plant.categories = Category.find(params[:plant][:category_ids])

    if @plant.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @plant = Current.user.plants.find(params[:id])
    @categories = Current.user.categories
  end

  def update
    # Ensure category_ids is an array (in case of unselected checkboxes)
    params[:plant][:category_ids] ||= []

    @categories = Category.find(params[:plant][:category_ids])

    if @plant.update(plant_params)
      redirect_to root_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @plant.destroy
    redirect_to root_path
  end

  private
    def set_plant
      @plant = Current.user.plants.find(params[:id])
    end

    def plant_params
      params.expect(plant: [ :common_name, :taxonomic_name, category_ids: [] ])
    end
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/views/plants/edit.html.erb
<% provide(:title, "Edit Plant") %>

<section class="is-fullscreen mb-6">
  <div class="container is-vcentered">
    <div class="columns is-centered">
      <div class="column is-one-third">
        <%= form_with(model: @plant, url: plant_path) do |form| %>
          <div class="box m-3 p-5">
            <p class="is-size-2 has-text-weight-medium block">Edit Plant</p>

            <%= render 'shared/error_messages', object: form.object %>

            <div class="field">
              <%= form.label :common_name, class: "label" %>
              <div class="control">
                <%= form.text_field :common_name, autofocus: true, autocomplete: "common-name", class: "input" %>
              </div>
            </div>

            <div class="field">
              <%= form.label :taxonomic_name, class: "label" %>
              <div class="control">
                <%= form.text_field :taxonomic_name, autofocus: true, autocomplete: "taxonomic-name", class: "input" %>
              </div>
            </div>

           <div class="field">
              <%= form.label :categories, class: "label" %>
              <div class="checkboxes">
                <% @categories.each do |category| %>
                  <div class="checkbox">
                    <%= form.check_box :category_ids, { multiple: true }, category.id, nil %>
                    <label for="category_ids_<%= category.id %>" class="checkbox">
                      <%= category.name %>
                    </label>
                  </div>
                <% end %>
              </div>
            </div>
            <br>
            <div class="actions">
              <%= form.submit "Update", class: "button is-green has-text-white has-text-weight-semibold" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/plants/new.html.erb
<% provide(:title, "New Plant") %>

<section class="is-fullscreen mb-6">
  <div class="container is-vcentered">
    <div class="columns is-centered">
      <div class="column is-one-third">
        <%= form_with(model: @plant, url: plants_path) do |form| %>
          <div class="box m-3 p-5">
            <p class="is-size-2 has-text-weight-medium block">New Plant</p>

            <%= render 'shared/error_messages', object: form.object %>

            <div class="field">
              <%= form.label :common_name, class: "label" %>
              <div class="control">
                <%= form.text_field :common_name, autofocus: true, autocomplete: "common-name", class: "input" %>
              </div>
            </div>

            <div class="field">
              <%= form.label :taxonomic_name, class: "label" %>
              <div class="control">
                <%= form.text_field :taxonomic_name, autofocus: true, autocomplete: "taxonomic-name", class: "input" %>
              </div>
            </div>

            <div class="field">
              <%= form.label :categories, class: "label" %>
              <div class="checkboxes">
                <% @categories.each do |category| %>
                  <div class="checkbox">
                    <%= form.check_box :category_ids, { multiple: true }, category.id, nil %>
                    <label for="category_ids_<%= category.id %>" class="checkbox">
                      <%= category.name %>
                    </label>
                  </div>
                <% end %>
              </div>
            </div>
            <br>
            <div class="actions">
              <%= form.submit "Create", class: "button is-green has-text-white has-text-weight-semibold" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>