config/routes.rb
Rails.application.routes.draw do
  get "static_pages/home"
  resource :session, except: [ :new ]

  # keep commented out unless password mailers are needed
  # resources :passwords, param: :token


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker


  root "static_pages#home"

  get "terms-of-use",   to: "static_pages#terms"
  get "privacy-policy", to: "static_pages#privacy"
  get "password-reset", to: "static_pages#password_reset"

  get "signup",   to: "registrations#new"
  post "signup",  to: "registrations#create"
  get "login",    to: "sessions#new"
  get "settings", to: "registrations#edit"
  resource :registrations, except: [ :show ]
  resources :plants, except: [ :index, :show ]
  resources :categories, except: [ :show ]
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  validates :user, presence: true
  has_and_belongs_to_many :plants

  validates :name, presence: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Current.user.categories.order(created_at: :desc)
  end

  def new
    @category = Category.new
  end

  def create
    @category = Current.user.categories.new(category_params)

    if @category.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @category = Current.user.categories.find(params[:id])
  end

  def update
    @category = Current.user.categories.find(params[:id])

    if @category.update(category_params)
      redirect_to root_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    Current.user.categories.find(params[:id]).destroy
    redirect_to root_path, notice: "Category successfully destroyed."
  end

  private
    def category_params
      params.expect(category: [ :name, :user_id ])
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<div class="card p-4 is-flex is-flex-direction-column is-justify-content-space-between" id="plant-card">
  <div class="is-flex is-flex-direction-column is-justify-content-start mb-4">
    <p class="has-text-weight-semibold is-size-4"><%= "#{category.name}" %></p>
  </div>
  <div class="actions">
    <%= link_to "Edit", edit_category_path(category), class: "button is-green has-text-white has-text-weight-semibold", data: { turbo: "false" } %>
    <%= link_to "Delete", category_path(category), data: { "turbo-method": :delete, turbo_confirm: "Are you sure you want to delete this category?" }, class: "button is-red has-text-white has-text-weight-semibold" %>
  </div>
</div>

app/views/categories/edit.html.erb
<% provide(:title, "Edit Category") %>

<section class="is-fullscreen mb-6">
  <div class="container is-vcentered">
    <div class="columns is-centered">
      <div class="column is-one-third">
        <%= form_with(model: @category, url: category_path) do |form| %>
          <div class="box m-3 p-5">
            <p class="is-size-2 has-text-weight-medium block">Edit Category</p>

            <%= render 'shared/error_messages', object: form.object %>

            <div class="field">
              <%= form.label :name, class: "label" %>
              <div class="control">
                <%= form.text_field :name, autofocus: true, autocomplete: "name", class: "input" %>
              </div>
            </div>
            <br>
            <div class="actions">
              <%= form.submit "Update", class: "button is-green has-text-white has-text-weight-semibold" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/categories/index.html.erb
<% provide(:title, "All Categories") %>

<div class="section">
  <div class="is-flex is-flex-direction-column mb-6">
    <h1 class="is-size-2 is-size-3-mobile has-text-weight-semibold mb-2">All Categories (<%= @categories.count %>)</h1>  
    <div class="buttons">
      <%= link_to "Add Category", new_category_path, class: "button is-green has-text-white has-text-weight-semibold is-medium my-0 mx-0", data: { turbo: false } %>
    </div>
  </div>
   <div class="fixed-grid has-5-cols-desktop has-3-cols-tablet has-1-cols-mobile">
    <div class="grid">
      <%= render @categories %>
    </div>
  </div>
</div>

app/views/categories/new.html.erb
<% provide(:title, "New Category") %>

<section class="is-fullscreen mb-6">
  <div class="container is-vcentered">
    <div class="columns is-centered">
      <div class="column is-one-third">
        <%= form_with(model: @category, url: categories_path) do |form| %>
          <div class="box m-3 p-5">
            <p class="is-size-2 has-text-weight-medium block">New Category</p>

            <%= render 'shared/error_messages', object: form.object %>

            <div class="field">
              <%= form.label :name, class: "label" %>
              <div class="control">
                <%= form.text_field :name, autofocus: true, autocomplete: "name", class: "input" %>
              </div>
            </div>
            <br>
            <div class="actions">
              <%= form.submit "Create", class: "button is-green has-text-white has-text-weight-semibold" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>