config/routes.rb
Rails.application.routes.draw do
  get "static_pages/home"
  resource :session, except: [ :new ]

  # keep commented out unless password mailers are needed
  # resources :passwords, param: :token


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker


  root "static_pages#home"

  get "terms-of-use",   to: "static_pages#terms"
  get "privacy-policy", to: "static_pages#privacy"
  get "password-reset", to: "static_pages#password_reset"

  get "signup",   to: "registrations#new"
  post "signup",  to: "registrations#create"
  get "login",    to: "sessions#new"
  get "settings", to: "registrations#edit"
  resource :registrations, except: [ :show ]
  resources :plants, except: [ :index, :show ]
  resources :categories, except: [ :show ]
end

app/views/layouts/_footer.html.erb
<footer class="footer is-vcentered mt-6 is-green">
  <div class="content has-text-centered">
    <div class="mb-3 has-text-white">
      <%= mail_to "plantsortapp@gmail.com", "Contact", class: "has-text-white footer-link"%> |
      <%= link_to "Terms of Use", terms_of_use_path, class: "has-text-white footer-link"%> |
      <%= link_to "Privacy Policy", privacy_policy_path, class: "has-text-white footer-link"%> |
      <%= link_to "View Source Code", "https://github.com/onathjan/plantsort", target: :blank, class: "has-text-white footer-link" %>
    </div>
    <p class="has-text-white">&copy; 2024 PlantSort. Enjoy the rest of your <%= Date.today.strftime("%A") %>!</p>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar px-5 py-3" role="navigation" aria-label="main navigation" data-controller="mobile-menu">
  <div class="navbar-brand">
    <%= link_to "PlantSort", root_path, class: "has-text-green has-text-weight-semibold is-size-2" %>

    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-action="click->mobile-menu#toggleMenu">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div class="navbar-menu" data-mobile-menu-target="menu">
    <div class="navbar-end">
      <% if authenticated? %>
        <div class="navbar-item has-text-centered">
          <%= link_to "Manage Categories", categories_path, class: "button is-white has-text-green has-text-weight-semibold mx-0 p-2" %>
        </div>
        <div class="navbar-item has-text-centered">
          <%= link_to "Settings", settings_path, class: "button is-white has-text-green has-text-weight-semibold mx-0 p-2" %>
        </div>
        <div class="navbar-item has-text-centered">
          <%= link_to "Log Out", session_path, data: { "turbo-method": :delete }, class: "button is-green has-text-white has-text-weight-semibold mx-0" %>
      <% else %>
        <div class="navbar-item has-text-centered">
          <%= link_to "Log In", login_path, class: "button is-white has-text-green has-text-weight-semibold mx-0 p-2" %>
        </div>

        <div class="navbar-item has-text-centered">
          <%= link_to "Sign Up For Free", signup_path, class: "button is-green has-text-white has-text-weight-semibold mx-0" %>
        </div>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/_notices.html.erb
<% if alert %>
  <div class="notification alert-message m-4 p-4" id="alert-message" data-controller="flash-message" data-flash-message-target="notification">
    <button class="delete" data-action="click->flash-message#close"></button>
    <p class="is-size-6 has-text-white has-text-weight-semibold"><%= alert %></p>
  </div>
<% elsif notice %>
  <div class="notification notice-message m-4 p-4" data-controller="flash-message" data-flash-message-target="notification">
    <button class="delete" data-action="click->flash-message#close"></button>
    <p class="is-size-6 has-text-white has-text-weight-semibold"><%= notice %></p>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html data-theme="light">
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="description" content="PlantSort is a free, open-source tool that helps you easily organize and manage the plants you grow with intuitive categories and a visually dynamic interface.">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/leaf.png" type="image/png">
    <link rel="apple-touch-icon" href="/leaf.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :application, "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag :custom_styling, "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag :bulma, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= render "layouts/notices" %>
    <%= yield %>
    <%= render "layouts/footer" %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>